version=1.0.0

lang=cn

TARGETS=indexEngine

indexEngine:
		g++ t_indexEngine.cpp -o t_indexEngine ../indexEngine.cpp -I /home/lscm/codebase/ilplib/include/ -I /home/lscm/codebase/izenelib/include/ -lboost_system -lboost_filesystem /home/lscm/codebase/ilplib/source/knlp/normalize.cpp
